[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "HECATE"
version = "0.0.1"
description = "HECATE"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]